### PR TITLE
Re-generating fact sets which were missing the mountpoints fact

### PR DESCRIPTION
**Pull request by hbrown-uiowa**

### CODE REVIEW

**Comment by hbrown-uiowa** [comment]
centos9/rh9/oracle9 still need to be re-done

**Comment by smortex** [comment]
I only see updated factsets in your PR, did you tuned something to have these facts are is a previous change enabling them and they where just waiting to be "refreshed"?

**Comment by hbrown-uiowa** [comment]
The facter gem needs the sys-filesystems gem in order to generate the mountpoints fact. However, the facter gem doesn't add it as a runtime dependency since the facter team didn't want to require folks to need a C compiler to use facter.

An earlier PR (#206) added in the sys-filesystem gem, so going forward the mountpoints fact will get generated. This PR was to fix most of the earlier generated factsets to include the missing mountpoints fact.

**Review by smortex — APPROVED** [review]
Thanks for the clarification!  LGTM!

**Pull request merged**
