### PR TITLE
Rebuild RHEL facts on Vagrant continued

### PR DESCRIPTION
**Pull request by zilchms**
As @yakatz is constricted on time right now, I contiued on his PR and tried to fix the comments of the reviews while preserving the purpose of his PR. This includes a rebase on the current master branch.

Includes: #277

### CODE REVIEW

**Comment by zilchms** [comment]
@yakatz can I get you to spend 5 minutes reviewing this real quick and giving it a thumbs up, if you think its ok? If this gets merged your PR will be merged as well, just as a heads-up :)

**Comment by yakatz** [comment]
I will try to look at it tonight (I was also sick last week and got even further behind). Did you generate the facts using the script or make the changes by hand? Hand changes are probably fine, but will get messed up next time the script is run - I was trying to work out the bugs through the script...

**Comment by zilchms** [comment]
I removed the changes that basically only changed device sizes etc by hand, those will change for everyone using the script everytime anyway (at least I think so). Some of the Virtualbox vs oVirt values might need changes, so those could be added. I tried to make everything as consistent as possible, but might have made some mistakes/ missed some stuff.
Good luck and get well soon (or stay well) :)

**Comment by yakatz** [comment]
I just see an issue with the Vagrantfile itself

**Comment by zilchms** [comment]
Ok, what issue do you see? I havent touched that, that should be your originial PRs vagrantfile I think (unless I overlooked something while rebasing)

**Comment by yakatz** [comment]
Looks like a rebase issue then

**Comment by yakatz** [comment]
I am working on this again from scratch using the scripts - not touching anything manually - so that it will be easily reproducible in the future.

**Comment by yakatz** [comment]
Fresh eyes are always good - I found the real reason the IPv6 facts are missing: these RHEL "boxes" ship with `net.ipv6.conf.all.disable_ipv6 = 1`. Just changing that automatically reenabled IPv6 and the facts are properly created.

**Comment by zilchms** [comment]
discontinued in favor of #304

**Pull request closed without merging**
