### PR TITLE
adding in facts for 4.5

### PR DESCRIPTION
**Pull request by hbrown-uiowa**

### CODE REVIEW

**Review by jhoblitt — COMMENTED** [review]
This seems reasonable but if we are going to make a new release, should we include fedora 39?

**Comment by hbrown-uiowa** [comment]
I checked for a fedora 39 vagrant box and there is only an arm one right now. It seems to take a month or two for the generic/fedoraXX image to show up in the vagrant box list.

**Review by jhoblitt — APPROVED** [review]
OK, seems like this is the best we can do at the moment excluding windows.

**Comment by bastelfreak** [comment]
@hbrown-uiowa sorrry, I missed your PR. Can you rebaae please?

**Pull request merged**
