### PR TITLE
Remove EoL CentOS 7 factsets

### PR DESCRIPTION
**Pull request by bastelfreak**
We announced that in https://voxpupuli.org/blog/2024/05/08/CentOS-7-CentOS-Stream-8-deprecation/

### CODE REVIEW

**Comment by bastelfreak** [comment]
we should keep this open until we do the next major release

**Comment by bastelfreak** [comment]
I would like to merge https://github.com/voxpupuli/facterdb/pull/266 first

**Review by tuxmea — APPROVED** [review]

**Comment by jhoblitt** [comment]
https://www.youtube.com/watch?v=DscJ5PFkZxQ

Its not dead for another 3 weeks...

**Comment by bastelfreak** [comment]
I know, but https://voxpupuli.org/blog/2024/05/08/CentOS-7-CentOS-Stream-8-deprecation/ and we had to do a major release anyways :)

**Comment by jhoblitt** [comment]
Thanks for breaking my CI :)

**Comment by bastelfreak** [comment]
why do you pull in random major releases without testing :)

**Comment by jhoblitt** [comment]
Everyone is a critic...

**Comment by jhoblitt** [comment]
My control repo pulls in `facterdb` via `voxpupuli-test`.

```ruby
  gem 'voxpupuli-test', '~> 5.4',  require: false
```

https://github.com/voxpupuli/voxpupuli-test/blob/99769f2cd30aabed8d32d9efc010f162c608b316/voxpupuli-test.gemspec#L20

However, in my local `Gemfile.lock`, the `< 2` doesn't seem to be reflected.

```
...
    voxpupuli-test (5.5.0)
      facterdb (>= 1.4.0)
...
```

Which doesn't seem correct.  Maybe this is a limitation of #add_runtime_dependency?

**Comment by jhoblitt** [comment]
My guess is that the issue is having a constraint of `< 2` basically means `< (any)` which is a no-op and that `< 2.0` would behave as expected.

**Comment by jhoblitt** [comment]
Well `<  2` works as expected in my control repo's `Gemfile`.... so that theory is out...
```
  gem 'facterdb', '< 2', require: false # 3.0.0 drops support for EL7
```

**Pull request merged**
