### PR TITLE
feat: add facts for debian-12

### LINKED ISSUE #279: Debian 12 support
There seems to be no support for debian 12 (bookworm) yet.

### PR DESCRIPTION
**Pull request by TheMeier**
fixes #279

### CODE REVIEW

**Review by kenyon — COMMENTED** [review]
Shall we also update the coverage table in the README?

**Comment by TheMeier** [comment]
> Shall we also update the coverage table in the README?

Done

**Review by kenyon — APPROVED** [review]
LGTM but I don't know how acceptable it is to be not using puppetlabs packages.

**Comment by TheMeier** [comment]
well we were asking for some time
https://puppetcommunity.slack.com/archives/C0W298S9G/p1688463627666479
https://app.slack.com/client/T0AQJ2CTU/C0W298S9G/thread/C0W298S9G-1688463627.666479
https://puppetcommunity.slack.com/archives/C0W298S9G/p1690547752195069
https://puppet.atlassian.net/jira/software/c/projects/PA/issues/PA-4995

instead of buliding processes for the well known regular os update cycles puppetlabs seems to habe opted for a reactionary process, catering to the paying enterprise customers:
> I checked in with the teams and no this is not currently on the road map or prioritized.
> If we can get details of who requires this we can make a case if there is a big enough requirement 

> There has to be enough usage from the community for us to commit the resources. Unfortunately, what we see is that  something like 85+% of our deployments are on RHEL and Ubuntu, with Debian being a very small percentage.

i would appreciate if voxpupuli could take the open source/agile approach and go ahead with this change, and revert the workarounds once the puppetlabs repos/packages drop. i do volunteer to provide a MR then

**Comment by TheMeier** [comment]
any updates here?

**Comment by bastelfreak** [comment]
I think for a start this is fine. We can regenerate them when puppet decides to support modern operating systems.

**Comment by TheMeier** [comment]
@bastelfreak thanks for merging, any change for a new release soon?

**Comment by kajinamit** [comment]
@bastelfreak sorry for duplicate ping but I'm wondering if we can have a new release with this change, so that we can enable unit tests with Debian 12.

**Pull request merged**
