### PR TITLE
Drop Facter 3 and older factsets

### PR DESCRIPTION
**Pull request by bastelfreak**
Puppet 7 is the oldest supported Puppet version. It vendors Facter 4. The facterdb performance depends on the amount of factsets so it makes sense to get rid of the legacy factsets.

### CODE REVIEW

**Review by ekohl — COMMENTED** [review]
The main reason I'm in favor of this is faster load times at runtime.

Since we need to update the README as well and do a major version bump, perhaps it's a good time to revisit https://github.com/voxpupuli/facterdb/pull/262.

**Comment by yakatz** [comment]
My browser was really unhappy trying to open the diff for this PR :-P
There are a few places in `get_facts.sh` where `puppet6` is mentioned in a comment. It probably wouldn't hurt to change those to the correct strings.

**Comment by yakatz** [comment]
> I did a rebase. I'm not sure why some of the tests fail 🤔 someone has an idea?

When I change `let(:facter_version) { '4.0.0' }` to `let(:facter_version) { '4.0.52' }` which is the version the facts were generated with, it succeeds.

**Comment by bastelfreak** [comment]
ah lol, yes. Thanks!

**Comment by bastelfreak** [comment]
IMO this is ready. I ensured that all modern facts are up2date and did a new minor release. I think we can drop the old stuff now.

**Comment by binford2k** [comment]
I haven't looked at the actual file changes, but in principle I'm in favor of dropping the old versions. They aren't changing, so if people need to use them, they can pin to an older release.

**Comment by TheMeier** [comment]
I'm ok with dropping facter 3. Puppet 7 was released over 3 years ago, puppet 6 is EOL for over a year

**Review by binford2k — APPROVED** [review]
I haven't looked at the actual file changes, but in principle I'm in favor of dropping the old versions. They aren't changing, so if people need to use them, they can pin to an older release.

**Review by jstraw — APPROVED** [review]

**Pull request merged**
